In [22]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [12]:
a = np.array([
    [0.3, 0.2, 1],
    [0.8, 0.9, 0.1],
    [0.1, 0.2, 0.1]
])

b = np.array([
    [0.1, 0.9],
    [1.0, 0.2]
])
print(a)
print(b)

[[0.3 0.2 1. ]
 [0.8 0.9 0.1]
 [0.1 0.2 0.1]]
[[0.1 0.9]
 [1.  0.2]]


In [17]:
np.sum(np.multiply(a[:2,:2], b))

1.19

In [18]:
np.sum(np.multiply(a[1:,1:], b))

0.4

In [19]:
np.sum(np.multiply(a[:2,1:], b))

1.84

In [20]:
np.sum(np.multiply(a[1:,1:], b))

0.4

In [25]:
encoder_input = layers.Input(shape=(64, 64, 3))
x = layers.Conv2D(64, 11, strides=2, activation="relu", padding="valid")(encoder_input)
x = layers.MaxPooling2D(pool_size=(2,2), strides=1, padding='valid')(x)
encoder = keras.Model(inputs=encoder_input, outputs=x, name='encoder')
encoder.summary()

Model: "encoder"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_3 (InputLayer)         [(None, 224, 224, 3)]     0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 224, 224, 64)      23296     
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 223, 223, 64)      0         
Total params: 23,296
Trainable params: 23,296
Non-trainable params: 0
_________________________________________________________________


In [29]:
decoder = keras.Sequential([
    layers.Input(shape=(64, 64, 3)),
    layers.Conv2D(64, 11, strides=2, activation="relu", padding="valid"),
    layers.MaxPooling2D(pool_size=(2,2), strides=2, padding='valid'),
    layers.Conv2D(64, 9, strides=1, activation="relu", padding="same"),
    layers.Flatten(),
    layers.Dense(10, activation="relu")
], name="decoder")
decoder.summary()

Model: "decoder"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_7 (Conv2D)            (None, 27, 27, 64)        23296     
_________________________________________________________________
max_pooling2d_6 (MaxPooling2 (None, 13, 13, 64)        0         
_________________________________________________________________
conv2d_8 (Conv2D)            (None, 13, 13, 64)        331840    
_________________________________________________________________
flatten_1 (Flatten)          (None, 10816)             0         
_________________________________________________________________
dense_1 (Dense)              (None, 10)                108170    
Total params: 463,306
Trainable params: 463,306
Non-trainable params: 0
_________________________________________________________________
